### ISSUE TITLE
Add name of map output to the Create Risk Map tool help

### ISSUE THREAD

**Issue by DeborahRoth** [Esri/transportation-safety-tools#34]
@jmhauck 

Include the name of the map that is to be exported in the help documentation of the Create Risk Map tool. Perhaps in the help for the *output map folder* parameter?

Another option/addition would be to force the mxd to open at the end of running the tool.

FYI: @jessnoo

**Comment by chris-fox** [comment]
With changes to the behavior of this tool for Pro, this enhancement no longer applies.
