### ISSUE TITLE
assign crashes, check_criteria should avoid using the OID field

### ISSUE THREAD

**Issue by jmhauck** [Esri/transportation-safety-tools#41]
field_oid = str(arcpy.Describe(sorted_features_layer).OIDFieldName)
            flds = [f.name for f in arcpy.ListFields(sorted_features_layer) if f.name != field_oid]

**Comment by pLeBlanc93** [comment]
Is [this](https://github.com/Esri/transportation-safety-tools/blob/master/source/CrashAssignment.py#L455) the line of code that's causing an issue? This seems similar to the Join Field issues ([here](https://github.com/ArcGIS/utilities-telco-solutions/issues/155) and [here](https://github.com/ArcGIS/local-government-toolbox/issues/45)) we ran into: internal validation is no longer ignoring invalid field types (e.g. OID). Does `Delete Identical` fail at 10.4 when an OID field is passed to it?

An alternative approach to disallowing OID fields would be to check the [`type`](http://desktop.arcgis.com/en/desktop/latest/analyze/arcpy-classes/field.htm) property on field objects:
```python
flds = [f.name for f in arcpy.ListFields(sorted_features_layer) if f.type != "OID"]
```

**Comment by allisonmuise** [comment]
is this a 10.4-specific issue?

**Comment by chris-fox** [comment]
This is resolved in the February 2016 release
