### ISSUE TITLE
assign crashes assignment not adding up

### ISSUE THREAD

**Issue by jessnoo** [Esri/transportation-safety-tools#55]
when assign crashes finishes, reports that the total number of crashes doesn't equal assigned + unassigned. need to figure out what's going on here

![image](https://cloud.githubusercontent.com/assets/6181441/17674400/38e2be92-62da-11e6-9543-46b2a41e863d.png)

**Comment by jmhauck** [comment]
@jessnoo could you help me understand how the sample data for #54 was generated? I will test against the full states data and all route types to see if the problem starts there. However, when I run BasicSegmentation on Prince George's county only the result dataset I get is quite different than what was attached to #54 and I don't reproduce this issue with that data.

**Comment by jmhauck** [comment]
@jessnoo I ran BasicSegmentation on the full states data and then ran Assign Crashes and was unable to reproduce the situation above. I received the email with a screenshot of your inputs and will dig through it further.

**Comment by jmhauck** [comment]
@jessnoo so it ended up being a PY3 Pro, vs PY2 Map issue. We were calling SelectLayerByAttribute then creating an UpdateCursor. In Pro the cursor does not honor the selection. Modified it to pass the where clause directly to the cursor.

**Comment by jessnoo** [comment]
validated
